name: edu_ui_assessment
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/data/subjects_quiz_data.json
    - assets/images/

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit/static/Outfit-Thin.ttf
          weight: 100
        - asset: assets/fonts/Outfit/static/Outfit-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Outfit/static/Outfit-Light.ttf
          weight: 300
        - asset: assets/fonts/Outfit/static/Outfit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Outfit/static/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit/static/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Outfit/static/Outfit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Outfit/static/Outfit-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Outfit/static/Outfit-Black.ttf
          weight: 900

    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi/Satoshi-Black.otf
          weight: 900
        - asset: assets/fonts/Satoshi/Satoshi-BlackItalic.otf
          weight: 900
          style: italic
        - asset: assets/fonts/Satoshi/Satoshi-Bold.otf
          weight: 700
        - asset: assets/fonts/Satoshi/Satoshi-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/Satoshi/Satoshi-Italic.otf
          style: italic
        - asset: assets/fonts/Satoshi/Satoshi-Light.otf
          weight: 300
        - asset: assets/fonts/Satoshi/Satoshi-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/Satoshi/Satoshi-Medium.otf
          weight: 500
        - asset: assets/fonts/Satoshi/Satoshi-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/Satoshi/Satoshi-Regular.otf
          weight: 400
